sonar.organization=sawssen19
sonar.projectKey=Sawssen19_PFE

# Information du projet
sonar.projectName=PFE Kollecta
sonar.projectVersion=1.0

# Emplacement du code source
sonar.sources=server/src,kollecta/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

# Encodage
sonar.sourceEncoding=UTF-8