apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: kollecta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sawssen19/kollecta-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgres-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: kollecta
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000